### ISSUE TITLE
Exception message error  in function _define_increments in loader.py

### ISSUE THREAD

**Issue by TLESORT** [arthurdouillard/continuum#11]
The Exception is raised if "not nb_tasks.is_integer()" an the message is :
"The tasks won't have an equal number of classes"
                f" with {len(self.class_order)} and increment {increment}"

I suspect a mismatch between exception condition and message :)

**Comment by arthurdouillard** [comment]
Unless I made a mistake, I think it's right.

If there are 10 classes, and an increment of 3, `nb_tasks` will be `3.333...`, thus not an integer. This means that not all tasks will have the same number of new classes.

In this case, the user should provide  fine-grained increments: *e.g.* `[3, 3, 3, 1]`

**Comment by TLESORT** [comment]
OK I understand now
